// Generate a unique ID for members
const generateMemberId = (index) => `member-${index + 1}`;

// Create mock trip data
export const mockTrips = [
  {
    id: "1",
    name: "Summer in Paris",
    destination: "Paris, France",
    startDate: "2023-07-15",
    endDate: "2023-07-25",
    description: "A 10-day adventure exploring the City of Light",
    members: [
      {
        id: generateMemberId(0),
        name: "Alex Johnson",
        email: "alex@example.com",
      },
      {
        id: generateMemberId(1),
        name: "Jamie Smith",
        email: "jamie@example.com",
      },
      {
        id: generateMemberId(2),
        name: "Taylor Brown",
        email: "taylor@example.com",
      },
      {
        id: generateMemberId(3),
        name: "Jordan Lee",
        email: "jordan@example.com",
      },
    ],
    expenses: [
      {
        id: "exp-1",
        title: "Flight Tickets",
        amount: 1200,
        paidBy: generateMemberId(0),
        splitWith: [
          generateMemberId(0),
          generateMemberId(1),
          generateMemberId(2),
          generateMemberId(3),
        ],
        category: "transportation",
        date: "2023-05-20",
      },
      {
        id: "exp-2",
        title: "Hotel Reservation",
        amount: 1800,
        paidBy: generateMemberId(1),
        splitWith: [
          generateMemberId(0),
          generateMemberId(1),
          generateMemberId(2),
          generateMemberId(3),
        ],
        category: "accommodation",
        date: "2023-05-22",
      },
    ],
    checklist: [
      {
        id: "check-1",
        title: "Passport",
        completed: true,
        category: "documents",
        assignedTo: generateMemberId(0),
        createdAt: "2023-05-15T10:30:00Z",
      },
      {
        id: "check-2",
        title: "Travel Insurance",
        completed: false,
        category: "documents",
        assignedTo: generateMemberId(1),
        createdAt: "2023-05-15T10:35:00Z",
      },
      {
        id: "check-3",
        title: "Power Adapters",
        completed: false,
        category: "electronics",
        assignedTo: "unassigned",
        createdAt: "2023-05-15T10:40:00Z",
      },
    ],
    timeline: [
      {
        id: "time-1",
        title: "Departure Flight",
        description: "AF1234 from JFK to CDG",
        date: "2023-07-15",
        time: "10:30",
        completed: false,
        createdAt: "2023-05-15T11:00:00Z",
      },
      {
        id: "time-2",
        title: "Check-in at Hotel",
        description: "Hotel de Paris, 15 Rue de Rivoli",
        date: "2023-07-15",
        time: "16:00",
        completed: false,
        createdAt: "2023-05-15T11:05:00Z",
      },
      {
        id: "time-3",
        title: "Eiffel Tower Visit",
        description: "Booked tickets for sunset view",
        date: "2023-07-16",
        time: "19:00",
        completed: false,
        createdAt: "2023-05-15T11:10:00Z",
      },
    ],
    locations: [
      {
        id: "loc-1",
        name: "Eiffel Tower",
        address: "Champ de Mars, 5 Avenue Anatole France, 75007 Paris",
        notes: "Open 9:00 AM - 12:45 AM. Book tickets in advance.",
        category: "attraction",
        createdAt: "2023-05-15T12:00:00Z",
      },
      {
        id: "loc-2",
        name: "Louvre Museum",
        address: "Rue de Rivoli, 75001 Paris",
        notes: "Closed on Tuesdays. Free entry on first Sunday of each month.",
        category: "attraction",
        createdAt: "2023-05-15T12:05:00Z",
      },
    ],
    polls: [
      {
        id: "poll-1",
        question: "Which restaurant should we go to for our first dinner?",
        options: [
          {
            id: "opt-1",
            text: "Le Jules Verne",
            votes: [generateMemberId(0), generateMemberId(3)],
          },
          { id: "opt-2", text: "Café de Flore", votes: [generateMemberId(1)] },
          { id: "opt-3", text: "L'Ambroisie", votes: [generateMemberId(2)] },
        ],
        createdAt: "2023-05-15T13:00:00Z",
        isActive: true,
      },
    ],
  },
  {
    id: "2",
    name: "Tokyo Adventure",
    destination: "Tokyo, Japan",
    startDate: "2023-09-10",
    endDate: "2023-09-20",
    description: "Exploring the vibrant city of Tokyo",
    members: [
      {
        id: generateMemberId(0),
        name: "Alex Johnson",
        email: "alex@example.com",
      },
      {
        id: generateMemberId(4),
        name: "Morgan Chen",
        email: "morgan@example.com",
      },
      {
        id: generateMemberId(5),
        name: "Casey Wong",
        email: "casey@example.com",
      },
    ],
    expenses: [],
    checklist: [],
    timeline: [],
    locations: [],
    polls: [],
  },
  {
    id: "3",
    name: "Italian Road Trip",
    destination: "Italy",
    startDate: "2023-10-05",
    endDate: "2023-10-15",
    description: "Road trip through Tuscany and the Amalfi Coast",
    members: [
      {
        id: generateMemberId(0),
        name: "Alex Johnson",
        email: "alex@example.com",
      },
      {
        id: generateMemberId(1),
        name: "Jamie Smith",
        email: "jamie@example.com",
      },
    ],
    expenses: [],
    checklist: [],
    timeline: [],
    locations: [],
    polls: [],
  },
];

export const testData = {
  timezone: "Europe/Paris",
  offset: "+02:00",
  language: "French",
  currency: "Euro (EUR)",
  name: "Paris",
  country: "France",
  location: {
    lat: 48.8566,
    lng: 2.3522,
  },
  tips: [
    "Most museums are closed on Mondays or Tuesdays",
    "Tipping is not required but rounding up is appreciated",
    "The Paris Museum Pass can save money if you plan to visit multiple museums",
    "Metro tickets can be purchased in bundles for a discount",
    "Many restaurants offer fixed-price lunch menus that are a good value",
  ],
  phrases: [
    { phrase: "Hello", translation: "Bonjour" },
    { phrase: "Thank you", translation: "Merci" },
    { phrase: "Excuse me", translation: "Excusez-moi" },
    { phrase: "Do you speak English?", translation: "Parlez-vous anglais?" },
    { phrase: "How much is this?", translation: "Combien ça coûte?" },
  ],
  weather: {
    current: {
      temp: 22,
      feels_like: 23,
      humidity: 65,
      wind_speed: 12,
      condition: "partly-cloudy",
      description: "Partly cloudy",
    },
    daily: [
      {
        date: "2023-07-15",
        temp_max: 24,
        temp_min: 18,
        condition: "sunny",
        description: "Sunny",
        precipitation: 0,
      },
      {
        date: "2023-07-16",
        temp_max: 26,
        temp_min: 19,
        condition: "partly-cloudy",
        description: "Partly cloudy",
        precipitation: 10,
      },
      {
        date: "2023-07-17",
        temp_max: 23,
        temp_min: 17,
        condition: "rainy",
        description: "Light rain",
        precipitation: 60,
      },
      {
        date: "2023-07-18",
        temp_max: 21,
        temp_min: 16,
        condition: "rainy",
        description: "Heavy rain",
        precipitation: 80,
      },
      {
        date: "2023-07-19",
        temp_max: 22,
        temp_min: 17,
        condition: "partly-cloudy",
        description: "Partly cloudy",
        precipitation: 20,
      },
      {
        date: "2023-07-20",
        temp_max: 25,
        temp_min: 18,
        condition: "sunny",
        description: "Sunny",
        precipitation: 0,
      },
      {
        date: "2023-07-21",
        temp_max: 27,
        temp_min: 20,
        condition: "sunny",
        description: "Sunny",
        precipitation: 0,
      },
    ],
    tripWeather: [
      {
        date: "2023-07-15",
        temp_max: 24,
        temp_min: 18,
        condition: "sunny",
        description: "Sunny",
        precipitation: 0,
      },
      {
        date: "2023-07-16",
        temp_max: 26,
        temp_min: 19,
        condition: "partly-cloudy",
        description: "Partly cloudy",
        precipitation: 10,
      },
      {
        date: "2023-07-17",
        temp_max: 23,
        temp_min: 17,
        condition: "rainy",
        description: "Light rain",
        precipitation: 60,
      },
      {
        date: "2023-07-18",
        temp_max: 21,
        temp_min: 16,
        condition: "rainy",
        description: "Heavy rain",
        precipitation: 80,
      },
      {
        date: "2023-07-19",
        temp_max: 22,
        temp_min: 17,
        condition: "partly-cloudy",
        description: "Partly cloudy",
        precipitation: 20,
      },
      {
        date: "2023-07-20",
        temp_max: 25,
        temp_min: 18,
        condition: "sunny",
        description: "Sunny",
        precipitation: 0,
      },
      {
        date: "2023-07-21",
        temp_max: 27,
        temp_min: 20,
        condition: "sunny",
        description: "Sunny",
        precipitation: 0,
      },
    ],
  },
};
