// Generate a unique ID for members
const generateMemberId = (index) => `member-${index + 1}`;

// Create mock trip data
export const mockTrips = [
  {
    id: "1",
    name: "Summer in Paris",
    destination: "Paris, France",
    startDate: "2023-07-15",
    endDate: "2023-07-25",
    description: "A 10-day adventure exploring the City of Light",
    members: [
      {
        id: generateMemberId(0),
        name: "Alex Johnson",
        email: "alex@example.com",
      },
      {
        id: generateMemberId(1),
        name: "Jamie Smith",
        email: "jamie@example.com",
      },
      {
        id: generateMemberId(2),
        name: "Taylor Brown",
        email: "taylor@example.com",
      },
      {
        id: generateMemberId(3),
        name: "Jordan Lee",
        email: "jordan@example.com",
      },
    ],
    expenses: [
      {
        id: "exp-1",
        title: "Flight Tickets",
        amount: 1200,
        paidBy: generateMemberId(0),
        splitWith: [
          generateMemberId(0),
          generateMemberId(1),
          generateMemberId(2),
          generateMemberId(3),
        ],
        category: "transportation",
        date: "2023-05-20",
      },
      {
        id: "exp-2",
        title: "Hotel Reservation",
        amount: 1800,
        paidBy: generateMemberId(1),
        splitWith: [
          generateMemberId(0),
          generateMemberId(1),
          generateMemberId(2),
          generateMemberId(3),
        ],
        category: "accommodation",
        date: "2023-05-22",
      },
    ],
    checklist: [
      {
        id: "check-1",
        title: "Passport",
        completed: true,
        category: "documents",
        assignedTo: generateMemberId(0),
        createdAt: "2023-05-15T10:30:00Z",
      },
      {
        id: "check-2",
        title: "Travel Insurance",
        completed: false,
        category: "documents",
        assignedTo: generateMemberId(1),
        createdAt: "2023-05-15T10:35:00Z",
      },
      {
        id: "check-3",
        title: "Power Adapters",
        completed: false,
        category: "electronics",
        assignedTo: "unassigned",
        createdAt: "2023-05-15T10:40:00Z",
      },
    ],
    timeline: [
      {
        id: "time-1",
        title: "Departure Flight",
        description: "AF1234 from JFK to CDG",
        date: "2023-07-15",
        time: "10:30",
        completed: false,
        createdAt: "2023-05-15T11:00:00Z",
      },
      {
        id: "time-2",
        title: "Check-in at Hotel",
        description: "Hotel de Paris, 15 Rue de Rivoli",
        date: "2023-07-15",
        time: "16:00",
        completed: false,
        createdAt: "2023-05-15T11:05:00Z",
      },
      {
        id: "time-3",
        title: "Eiffel Tower Visit",
        description: "Booked tickets for sunset view",
        date: "2023-07-16",
        time: "19:00",
        completed: false,
        createdAt: "2023-05-15T11:10:00Z",
      },
    ],
    locations: [
      {
        id: "loc-1",
        name: "Eiffel Tower",
        address: "Champ de Mars, 5 Avenue Anatole France, 75007 Paris",
        notes: "Open 9:00 AM - 12:45 AM. Book tickets in advance.",
        category: "attraction",
        createdAt: "2023-05-15T12:00:00Z",
      },
      {
        id: "loc-2",
        name: "Louvre Museum",
        address: "Rue de Rivoli, 75001 Paris",
        notes: "Closed on Tuesdays. Free entry on first Sunday of each month.",
        category: "attraction",
        createdAt: "2023-05-15T12:05:00Z",
      },
    ],
    polls: [
      {
        id: "poll-1",
        question: "Which restaurant should we go to for our first dinner?",
        options: [
          {
            id: "opt-1",
            text: "Le Jules Verne",
            votes: [generateMemberId(0), generateMemberId(3)],
          },
          { id: "opt-2", text: "Café de Flore", votes: [generateMemberId(1)] },
          { id: "opt-3", text: "L'Ambroisie", votes: [generateMemberId(2)] },
        ],
        createdAt: "2023-05-15T13:00:00Z",
        isActive: true,
      },
    ],
  },
  {
    id: "2",
    name: "Tokyo Adventure",
    destination: "Tokyo, Japan",
    startDate: "2023-09-10",
    endDate: "2023-09-20",
    description: "Exploring the vibrant city of Tokyo",
    members: [
      {
        id: generateMemberId(0),
        name: "Alex Johnson",
        email: "alex@example.com",
      },
      {
        id: generateMemberId(4),
        name: "Morgan Chen",
        email: "morgan@example.com",
      },
      {
        id: generateMemberId(5),
        name: "Casey Wong",
        email: "casey@example.com",
      },
    ],
    expenses: [],
    checklist: [],
    timeline: [],
    locations: [],
    polls: [],
  },
  {
    id: "3",
    name: "Italian Road Trip",
    destination: "Italy",
    startDate: "2023-10-05",
    endDate: "2023-10-15",
    description: "Road trip through Tuscany and the Amalfi Coast",
    members: [
      {
        id: generateMemberId(0),
        name: "Alex Johnson",
        email: "alex@example.com",
      },
      {
        id: generateMemberId(1),
        name: "Jamie Smith",
        email: "jamie@example.com",
      },
    ],
    expenses: [],
    checklist: [],
    timeline: [],
    locations: [],
    polls: [],
  },
];
